### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by ulidtko**
Followup from #10... @digitronik I'll kindly leave setup cleanup to you — just got [CI green][1] again:

image

3 issues mainly:
 * black formatting in console.py was triggering pre-commit hook (I left `__init__.py` untouched, but it's to be reformatted too);
 * outdated versions, Py 3.5 & 3.6 are EOL and not supported — updated to current;
 * double-layered "matrix": nox tried to test 4 versions in all 4 CI steps per each version — reconfigured to use current version from host (so, 4 test runs total instead of 16).

[1]: https://github.com/ulidtko/python-xrectsel/actions/runs/3143274025

### CODE REVIEW

**Review by digitronik — CHANGES_REQUESTED** [review]
Thanks for removing older python support and maintaining this project. 

I think you need to change `setup.cfg` as well.

**Comment by ulidtko** [comment]
@digitronik ok, done

**Review by digitronik — APPROVED** [review]

**Comment by digitronik** [comment]
@ulidtko frankly i'm not able to maintain most of my project due to lack of time. I added you as maintainer of this repo so in future at least you or me can maintain this. 
Thanks for your opensource contributions and maintaining code. 

kudos to you :+1:

**Comment by ulidtko** [comment]
1.5 tagged — on PyPI — tested, works as expected :rocket:

**Pull request merged**
